### ISSUE TITLE
Hyphens break highlighting

### ISSUE THREAD

**Issue by OmgImAlexis** [aaronellington/language-caddyfile#3]
![screen shot 2017-10-15 at 2 21 09 am](https://user-images.githubusercontent.com/6525926/31577081-a78355c2-b14f-11e7-9346-523d7da34321.png)

```caddy
0.0.0.0:5000 {
    header / {
        Strict-Transport-Security "max-age=7776000;"
    }        
}
```

**Comment by aaronellington** [comment]
Thank you for the feedback, I really appreciate it! This is now fixed and published to `apm`.
