### ISSUE TITLE
Caddyfile.development not Recognized

### ISSUE THREAD

**Issue by dodekeract** [aaronellington/language-caddyfile#7]
Is there anything this package can do to support that?

**Comment by aaronellington** [comment]
Looks like you may be able to add your own extension mapping: https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition

I'll go ahead and close this issue but feel free to let me know if this does not work for you.

**Comment by dodekeract** [comment]
@aaronellington Well, that wouldn’t work because it’s an extension, not a base name. I don’t want all `.development` files to be associated with caddy. 🙂

Anyway, if this is not fixable, then so be it.

**Comment by aaronellington** [comment]
This does work for me with a file named: `Caddyfile.development`.

```cson
  core:
    customFileTypes:
      'source.Caddyfile': [
        'Caddyfile.development',
      ],
```

I know it's still not super ideal but it works.
