### ISSUE TITLE
Not displaying correctly

### ISSUE THREAD

**Issue by Conor-Burns** [aaronellington/language-caddyfile#8]
Hi I don't know if this repo is still maintained, but I can't get this to work properly and this is the only plugin for caddy on atom.
![2019-03-03-123004_2560x1440_scrot](https://user-images.githubusercontent.com/41896852/53694506-21ac7700-3db0-11e9-8596-05adbd64be0f.png)

**Comment by FlorianWendelborn** [comment]
“Can’t get this to work” is a really useless issue description. I don’t see anything wrong with your screenshot, as it looks like it’s highlighting the Caddyfile.

Perhaps, if you expect other people to solve your problems for you, you should include a description of your problem.

**Comment by Conor-Burns** [comment]
Whoa sorry that I've pissed you off :/
But isn't this supposed to display another color for the server-name? I get three colors in total - instead of four. Is this a problem with my theme?  
![screenshot](https://user-images.githubusercontent.com/41896852/53695765-f0d43e00-3dbf-11e9-833f-5653c902b985.png)

**Comment by aaronellington** [comment]
@Conor-Burns Howdy! It does look like it might be your theme. Does it still happen if you temporarily change to the default theme?

Also, nice desktop enviornment :+1:

**Comment by Conor-Burns** [comment]
![2019-03-03-152841_2560x1440_scrot](https://user-images.githubusercontent.com/41896852/53696609-0b5ee500-3dc9-11e9-8ca1-49bf379b6239.png)

Yup was the syntax theme.
I think i might have found my new favorite atom theme xD

Thanks for your help!

PS: it's not a desktop environment its a window manager :P jk - yeah i3wm is really fun
